include:
  - board: nice_nano_v2
    shield: sofle_rgb_left
    # REMOVIDO: snippet: studio-rpc-usb-uart (Causa conflito com a matriz do Sofle V1)
    artifact-name: sofle_left_debug
  - board: nice_nano_v2
    shield: sofle_rgb_right
    artifact-name: sofle_right_debug
